<a href="https://colab.research.google.com/github/jihye-jeon2/python/blob/main/MissingValues%EA%B2%B0%EC%B8%A1%EC%B9%98%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

환경설정

In [4]:
#구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

#드라이브에 저장된 폰트 등록
import matplotlib as mpl
import matplotlib.pyplot as plt  #그래프를그리는 pylpot모듈
import matplotlib.font_manager as fm #폰트를 관리하는 모듈

#드라이브내 폰트경로
font_path='/content/drive/MyDrive/kwu (1)/빅데이터/dataPreProcesing/NanumGothic.ttf'

fm.fontManager.addfont(font_path)
mpl.rc('font',family='NanumGothic') #matplotlib 기본 폰트로 설정
plt.rcParams['axes.unicode_minus'] = False #마이너스기호가 깨지지않도록 유니코드 마이너스 비활성화

print("현재폰트:  ",plt.rcParams['font.family'])  #현재 적용된 폰트 이름 출력

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
현재폰트:   ['NanumGothic']

In [5]:
import pandas as pd # 데이터프레임 조작
import numpy as np #수치 계산 및 NaN(결측치) 처리
import matplotlib.pyplot as plt #그래프 시각화
import seaborn as sns #시각화

#타이타닉 데이터로드
titanic = pd.read_csv('/content/drive/MyDrive/kwu (1)/빅데이터/dataPreProcesing/train.csv')
print(titanic.shape)
titanic.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

실습1. 결측치 개념 이해

In [10]:
#결측치의 특성 확인
import numpy as np #np.nan 결측치 사용

#비교연산자
print(np.nan==np.nan) #결측치는 비교불가 / 자기자신과도 같지않다(없는존재이기때매)
print(np.nan==0)  #결측치 Nan은 0이 아니고 '값 없음'상태임
print(np.nan=="") #NaN은 빈문자열,공백이 아니고 '값없음'상태임

#올바른 결측치 확인 방법
print(pd.isnull(np.nan))  #pd.isnull 판다스문법의 isnull() 메서드사용
print(pd.notnull(np.nan)) #isnull의 반대 notnull null이 아닌지

#시리즈에서 결측치 확인
s=pd.Series([1,np.nan,3,None,5])  #각각이 결측치인지 아닌지 확인
display(s)
print(s.isnull().sum()) #False->0 / True->1

False
False
False
True
False

0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
dtype: float64

2

실습2.

In [12]:
# 기본 정보 확인
titanic.info() #non-Null이 891보다 작은 열에 결측치 존재

#열별 결측치 개수
missing_count=titanic.isnull().sum()
print(missing_count)
print(missing_count[missing_count>0]) #결측치가 1개 이상인행만

#결측치 비율 (%)
missing_ratio=(titanic.isnull().sum() / len(titanic) *100).round(1) #결측치수/전체행수 *100
print(missing_ratio)
print(missing_ratio[missing_ratio>0])

#전체 결측치 개수
total_missing=titanic.isnull().sum().sum() #열별 결측치 합계
print(f"전체 결측치 수:{total_missing}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
Age         177
Cabin       687
Embarked      2
dtype: int64
PassengerId     0.0
Survived        0.0
Pclass          0.0
Name            0.0
Sex             0.0
Age            19.9
SibSp           0.0
Parch           0.0
Ticket          0.0
Fare            0.0
Cabin          77.1
Embarked        0.2
dtype: float64
Age         19.9
Cabin       77.1
Embarked     0.2
dtype: float64
전체 결측치 수:866

실습3 결측치 시각화

In [14]:
## 막대 그래프로 결측치 비율 시각화
missing_ratio = titanic.isnull().mean() * 100
missing_ratio = missing_ratio[missing_ratio>0].sort_values(ascending=False)  #결측치 잇는 열만 선택 후 비율 내림차순 정렬
missing_ratio
plt.title
plt.ylable('결측치 비율(%)')
plt.xtickets(rotation=45) #결축 눈금 레이블을 45도 기울여서
plt.axhline(y=50,color='red',linestyle='--',alpha=0.5,label='50% 기준선')
plt.legend()
plt.tight_layout()
plt.show()

AttributeError: module 'matplotlib.pyplot' has no attribute 'ylable'

In [ ]:
#히트맵으로 결측치 패턴 시각화
plt.figure(figsize=(10,5))
sns.heatmap(titanic.isnull(), #isnull()로 결측치 위치를 True/False행렬로 변환 후 히트맵으로 시각화
            cmap='veridis', #색상테마:노란색(결측치=True) / 보라색(정상값=False)
            cbar=False,
            yticklabels=False
            )
plt.title('결측치 히트(노란색=결측치)')
plt.tight_layout()
plt.show()

실습4 결측치 대체 -fillna()

In [19]:
#고정값으로 대체: 범주형 열
print(titanic['Embarked'].mode([1])) #최빈값 함수는 mode()
titanic['Embarked'].fillna('S')  #최빈값 S로 대체하겟다 na(결측치)를 fill

#통계값으로 대체: 수치형 열
mean_age=titanic['Age'].mean()
median_age = titanic['Age'].median()

titanic['Age_filled']=titanic['Age'].fillna(median_age)

#대체 전후 비교
print('대체 전 결측치: ',titanic['Age'].isnull().sum())
print('대체 후 결측치: ',titanic['Age_filled'].isnull().sum())

#그룹별 통계값으로 대체:더 정밀한 방법 고민
#성별/등급별 중앙값으로 나이 대체
titanic['Age_group_filled']= titanic.groupby(['Sex','Pclass'])['Age'].transform(
    lambda x:x.fillna(x.median())
)
print(titanic.groupby(['Sex','Pcalss'])(['Age'].median())

SyntaxError: incomplete input (2368457291.py, line 20)

In [ ]:
실습5 결측치 대체-방향성 채우기

In [20]:
#시계열 데이터 예시:날짜별 탑승객 수
daily_passangers=pd.Series(
    [100,np.nan,np.nan,130,np.nan,150],
    index=pd.date_range('2026-01-01',periods=6)
)
print('원본:\n',daily_passengers)

#정방향으로 채우기 (ffill=forwardfill): 결측치를 바로 앞의 유효한 값으로 채움
print('\n ffill: \n',daily_passengers.ffill())

#역방향으로 채우기 (bfill=backward fill):결측치를 바로뒤의 유효한값으로 채움
print('\n bfill: \n',daily_passengers.bfill())

#보간법(interpolate):앞뒤 값 사이를 선형으로 계산해서 ㅐㅊ움,일정한 간격으로 증가하도록채워짐
print('\n interpolate: \n',daily_passengers.interpolate())

#시리즈 맨 첫값이 NaN이면 ffill로 채울수없음
s=Pd.pd.Series

NameError: name 'daily_passengers' is not defined

결측치 삭제 -dropna()

In [21]:
#dropna(): 결측치가 하나라도 잇는 행을 모두 삭제
df_dropped = titanic.dropna()
print(f"원본: {titanic.shape}")
print(f"드롭후: {df_dropped.shape}")

#열 삭제: 결측치 비율이 매우 높은 열은 행 삭제 대신 열 자체를 제거하는 것이 효과적
df_no_deck=titanic.drop(colimns=['Cabin'])
print(f"df_no_deck: {df_no_deck.shape}")

원본: (891, 14)
드롭후: (183, 14)

결측치가 잇는 상태로 계산하기

In [23]:
#결측치가 포함된 사칙연산: 결측치와의 연산 결과는 항상 NaN
s=pd.Series([10,np.nan,30,np.nan,50])
print(s+5)

#집게 함수(sun,mean 등)는 기본적으로 NaN을 무시하고 계산
print(s.sum())
print(s.mean())

#skipna=False로 설정하면 NaN이 하나라도 잇으면 결과도 NaN
print(s.sum(skipna=False))

#타이타닉: 결측치 없는 열끼리 더하면 정상계산
titanic['FamilySize'] = titanic['SibSp']+titanic['Parch']

#타이타닉 :결측치 잇는 열과의 연산
titanic['Test'] = titanic['Age']+titanic['Fare']
print(titanic['Test'].isnull().sum())

titanic=titanic.drop(columns=['Test'])

0    15.0
1     NaN
2    35.0
3     NaN
4    55.0
dtype: float64
90.0
30.0
nan
177

np.NaN vs pd.NA비교

In [27]:
#np.NaN을 정수 열에 삽입하면 열전체가 float으로 자동 변환됨
df=pd.DataFrame({'name':['Alice','Bob'],'age':[25,30]})
df.loc[0,'age']=np.nan
print(df.dtypes)
print(df)

#pd.NA + nullable integer(Int64) 를 사용하면 정수 타입 유지 가능
df2=pd.DataFrame({'name':['Alice','Bob'],'age':pd.array([25,30],dtype='int64')})
df2.loc[0,'age']=pd.NA
print(df2.dtypes)
print(df2)

#np.nan vs pd.NA 논리 연산 차이
print(True and np.nan) #np.nan qksghks
print(False and np.nan)

print(True and pd.NA) # 결과 불확실
print(False and pd.NA)

#실무에서 결측치 여부는 항상 isnull() 또는 isna() 사용
print(pd.isnull(np.nan))
print(pd.isnull(pd.NA))

name     object
age     float64
dtype: object
    name   age
0  Alice   NaN
1    Bob  30.0
name     object
age     float64
dtype: object
    name   age
0  Alice   NaN
1    Bob  30.0
nan
False
<NA>
False
True
True

In [ ]:
###타이타닉 결측치 전처리

In [28]:
titanic_clean=titanic.copy()

titanic_clean=titanic_clean.drop(columns=['Cabin'])

#Age 결측치 처리
titanic_clean['Age']=titanic_clean.groupby(['Sex','Pclass'])['Age'].transform(
    lambda x:x.fillna(x.median())
)

#Embarked 결측치 처리
titanic_clean['Embarked']=titanic_clean['Embarked'].fillna(
    titanic_clean['Embarked'].mode()[0]
)
#최종 결측치 현황 확인
print("전처리후결측치: ")
print(titanic_clean.isnull().sum()[titanic_clean.isnull().sum()>0])

print(f"\n원본 shape: {titanic.shape}")
print("전처리후 shape:{titanic_clean.shape}")

전처리후결측치:
Test    177
dtype: int64

원본 shape: (891, 16)
전처리후 shape:{titanic_clean.shape}

In [30]:
#Age가 결측인 승객만 필터링해서 결측치 발생 패턴 분석
age_missing =titanic[titanic['Age'].isnull()] #Age열이 NaN인 행만 추출
age_missing[['SibSp','Parch','Sex','Pclass']].describe()

#범주형 열 빈도 분석: 결측치가 어떤 그룹에서 발생햇는지 개수로 확인
print(age_missing['Sex'].value_counts())
print(age_missing['Pclass'].value_counts())
print(age_missing['SibSp'].value_counts())
print(age_missing['Parch'].value_counts())

Sex
male      124
female     53
Name: count, dtype: int64
Pclass
3    136
1     30
2     11
Name: count, dtype: int64
SibSp
0    137
1     26
8      7
3      4
2      3
Name: count, dtype: int64
Parch
0    157
2     12
1      8
Name: count, dtype: int64

In [ ]:
#위분석 결과 요약(결측치 발생 패턴 해석)
#Sex:male이 압도적으로 많음->나이기제를생략한 승객 대부분이 남성
#Pclass: 3등석이 가장 많음->저가 티켓승객일수록 개인정보 누락 가능성 높음
#SibSP/Parch : 0이대부분->가족없이 혼자 탑승한 승객에서 결측치가 마니 발생

#혼자 탑승한 3등석 남성

In [ ]:
#특정조건(혼자 탑승한 3등석남성)에해당하는 그룹의 평균나이계산
condition=(
    (titanic['Sex']=='male')&
    (titanic['Pclass']==3)&
    (titanic['SibSp']==0)&
    (titanic['Parch']==0)
)
group_mean_age=titanic[condition]['Age'].mean()

In [ ]:
#위조건을 만족하면서 동시에 Age가 결측인 행에만 평균나이를 채움
titanic.loc[condition&titanic['Age'].isnull(),'Age']=group_mean_age